language: node_js
node_js:
- 0.10
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm rebuild
- npm install -g grunt-cli
script: grunt default
env:
  global:
  - secure: AhTiE3wiPkfVsyo474yF/6Rx+fwqnfSpIrN1VQRNmf1R58uq8WplWNZwSKHECWahkxOC6KFL9pMt0e6L0Hu1PBJT791Yy8SD0Ax/9gK27ac7xpiMcW3lXIMSqSEams/2hWTuxVoE34Iapr7/RPTOPcbV8BkBWQ+oSVfiwajcks8=
  - secure: kpU6Dgdc3ARAE4odMO3Uvsor4YPYJtydHurWPMHsG8oA0XB9c1wi8aQ0o07oGW87KYIKaw7S7bBpZgmfzQziwt+LlFxNPivChbR/e9WX/k4NxqXEVxVjtJXAoJYY5JnHoktm4dzSeTAUnWqzfFHICeIFfpQ33Rs7JQb3U73kP1g=
  - secure: gLDqWuDi2yycrJV6fBMqpiJQtofSRutvNy5bVhZ3C1mlhbJXU6opdeTvXIP6TfMHKhal+FKmEjhG+rxBFE7nwbrAwlUNIIt0B8SaGkWfwf7lxn3rjv6tNA2YAjWRVw5B7WudcYEVpHrYtmz9TocK3BD1USlVOGx8g2BFLrsbR6Y=
  - secure: XX5PT4afTGfuV8PwmSjLzURZpQdh+Ko/AGoZ/XGh5KFJvdKnqaQUqWTwq+wihdLD9NijIV3o1Hr1opqvYAwkTA62kVA0MmiLX640CER1XPWMPtv1t+cgoHtLh6dRq2EJVapHwDI9I0zr8GevTJyw9124nU69XLYLnTig+B8aUgc=
  - secure: UNnw9SX1w27McFD9Fjj+BfPKXibAaJF+fAFMnvhAc2DwyWxJKMTGn8aE0BazPHFmD2ctQKwExFjuAoWOl3rxAgMlpC0HWDTYkI4AJIzPkypI0VwVsVYqTYDGMOjj0puvPxE97zHSULZ6Jpm9mgsWNVQdmu3e3ottVpzr0ZUMwXs=
