language: node_js
node_js:
- 0.10
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm rebuild
- npm install -g grunt-cli
script: grunt default
env:
  global:
  - secure:  "gLDqWuDi2yycrJV6fBMqpiJQtofSRutvNy5bVhZ3C1mlhbJXU6opdeTvXIP6TfMHKhal+FKmEjhG+rxBFE7nwbrAwlUNIIt0B8SaGkWfwf7lxn3rjv6tNA2YAjWRVw5B7WudcYEVpHrYtmz9TocK3BD1USlVOGx8g2BFLrsbR6Y="
  - secure:  "XX5PT4afTGfuV8PwmSjLzURZpQdh+Ko/AGoZ/XGh5KFJvdKnqaQUqWTwq+wihdLD9NijIV3o1Hr1opqvYAwkTA62kVA0MmiLX640CER1XPWMPtv1t+cgoHtLh6dRq2EJVapHwDI9I0zr8GevTJyw9124nU69XLYLnTig+B8aUgc="
  - secure:  "UNnw9SX1w27McFD9Fjj+BfPKXibAaJF+fAFMnvhAc2DwyWxJKMTGn8aE0BazPHFmD2ctQKwExFjuAoWOl3rxAgMlpC0HWDTYkI4AJIzPkypI0VwVsVYqTYDGMOjj0puvPxE97zHSULZ6Jpm9mgsWNVQdmu3e3ottVpzr0ZUMwXs="
